const ACCESS_TOKEN_LOCAL_STORAGE_KEY = 'access';
const REFRESH_TOKEN_LOCAL_STORAGE_KEY = 'refresh';

const TRANSACTION_REFERENCE_ID_SELLING_TO_CUSTOMER = 2;

export {
    ACCESS_TOKEN_LOCAL_STORAGE_KEY,
    REFRESH_TOKEN_LOCAL_STORAGE_KEY,
    TRANSACTION_REFERENCE_ID_SELLING_TO_CUSTOMER,
};
