const EASY_ERP_BASE_URL =
    process.env.NODE_ENV === 'development' ? 'http://localhost:8000/api' : '';

// Base urls
const EASY_ERP_AUTH_BASE_URL = '/auth';
const EASY_ERP_WAREHOUSE_BASE_URL = '/warehouse';
const EASY_ERP_REPAIRS_BASE_URL = '/repairs';

// Authentication
const EASY_ERP_LOGIN_URL = EASY_ERP_AUTH_BASE_URL + '/login';
const EASY_ERP_SIGNUP_URL = EASY_ERP_AUTH_BASE_URL + '/signup';
const EASY_ERP_PROFILE_URL = EASY_ERP_AUTH_BASE_URL + '/profile';
const EASY_ERP_PROFILE_PASSWORD_URL =
    EASY_ERP_AUTH_BASE_URL + '/profile/password';
const EASY_ERP_REFRESH_TOKEN_URL = EASY_ERP_AUTH_BASE_URL + '/token/refresh';

// Warehouse
const EASY_ERP_ARTICLES_URL = EASY_ERP_WAREHOUSE_BASE_URL + '/articles';
const EASY_ERP_INVENTORY_URL = EASY_ERP_WAREHOUSE_BASE_URL + '/inventory';
const EASY_ERP_TRANSACTIONS_URL = EASY_ERP_WAREHOUSE_BASE_URL + '/transactions';

export {
    EASY_ERP_BASE_URL,
    EASY_ERP_REPAIRS_BASE_URL,
    EASY_ERP_LOGIN_URL,
    EASY_ERP_SIGNUP_URL,
    EASY_ERP_PROFILE_URL,
    EASY_ERP_PROFILE_PASSWORD_URL,
    EASY_ERP_REFRESH_TOKEN_URL,
    EASY_ERP_ARTICLES_URL,
    EASY_ERP_INVENTORY_URL,
    EASY_ERP_TRANSACTIONS_URL,
};
